### ISSUE TITLE
Integrate with Chrome Console for API requests

### ISSUE THREAD

**Issue by luispabon** [RiperFr/sf2DebuggerChrome#5]
Wonderful extension! Although on its current incarnation I can only see how to use it on GET requests from the browser's URL bar, and not as any sort of request from an AJAX call from a JS based UI that talks to a symfony API.

**Comment by ztec** [comment]
It Should include all request (including ajax calls).
Do you have a step/byStep to reproduce ? An online page to see the bug ?

**Comment by luispabon** [comment]
Let me look at this more closely and will get back to you :+1: 

So in theory, loading up my HTML/JS UI that makes ajax calls to my API should trigger the presence of the extension's button on the address bar? 

(the UI is definitely using the dev controller)

**Comment by ztec** [comment]
Yes, any ajax calls should trigger the litle green icon of the extensions.

**Comment by luispabon** [comment]
Copy that; I'm currently rebuilding my dev env on docker so might take a while until I can check again. Will report back :+1:

**Comment by luispabon** [comment]
Must have been a temporary fluke. It works as it should. Sorry I wasted your time and thank you!

**Comment by ztec** [comment]
No wories :-)
